/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * 1 (bottom fifth of England) … 5 (top fifth)
 */
export type Band = number | null;
/**
 * @minItems 4
 * @maxItems 4
 */
export type Bbox = [unknown, unknown, unknown, unknown];
export type Lat = number;
export type Lon = number;
export type Coverage = number | null;
/**
 * Caveats that apply to this area
 */
export type Flags = string[];
export type Id = string;
export type Label = string;
export type Quality = string;
export type Role = string;
/**
 * 0–100, higher is better
 */
export type Score = number | null;
export type Theme = string;
export type Unit = string;
/**
 * Raw value in `unit`
 */
export type Value = number | null;
export type KeyFacts = IndicatorValue[];
export type LocalAuthority = string;
export type Lsoa21Cd = string;
export type LsoaName = string;
export type Msoa21Cd = string;
/**
 * Friendly MSOA name
 */
export type Neighbourhood = string | null;
export type Overall = number | null;
export type OverallPercentile = number | null;
export type Population = number;
export type Preset = string;
export type Region = string;
export type Strengths = IndicatorValue[];
export type Label1 = string;
/**
 * Better than this % of England's LSOAs
 */
export type Percentile = number | null;
/**
 * 0–100, higher is better
 */
export type Score1 = number | null;
export type Theme1 = string;
export type Themes = ThemeScore[];
export type UrbanRural = string;
export type Weaknesses = IndicatorValue[];
export type Code = string;
export type Level = "lsoa" | "msoa" | "lad" | "region";
export type Name = string;
export type Overall1 = number | null;
export type OverallPercentile1 = number | null;
export type Areas = ComparedArea[];
export type Preset1 = string;
/**
 * weight_share × score
 */
export type Contribution1 = number | null;
export type Indicators1 = IndicatorValue[];
export type Label2 = string;
export type Score2 = number | null;
export type Theme2 = string;
/**
 * Share of the overall weight, 0–1
 */
export type WeightShare = number;
export type Caveats = string[];
export type Contributions = Contribution[];
export type Lsoa21Cd1 = string;
export type Name1 = string;
export type Overall2 = number | null;
export type OverallPercentile2 = number | null;
export type Preset2 = string;
export type Sources = string[];
export type Caveats1 = string | null;
export type Description = string;
export type Direction = string;
export type Id1 = string;
export type Label3 = string;
export type Normalise = string;
export type Role1 = string;
export type Sources1 = string[];
export type Theme3 = string;
export type Unit1 = string;
export type Weight = number;
export type CompareWithinUrbanRural = boolean;
/**
 * west, south, east, north
 */
export type Bbox1 = [unknown, unknown, unknown, unknown] | null;
/**
 * LSOA/MSOA codes to outline
 */
export type Highlighted = string[];
/**
 * "overall", "theme:<theme>" or "indicator:<id>"
 */
export type Layer = string;
export type Category = string;
export type DistanceM = number;
export type Licence = string;
export type Name2 = string | null;
export type Source = string;
/**
 * Markers to show
 */
export type Pois = Poi[];
/**
 * LSOA code of the open area profile
 */
export type Selected = string | null;
export type Mode = "consumer" | "analyst";
export type Preset3 = string;
export type Code1 = string;
export type Name3 = string;
export type Note = string | null;
export type Shortlist = ShortlistItem[];
/**
 * west, south, east, north
 */
export type Bbox2 = [unknown, unknown, unknown, unknown] | null;
export type Code2 = string | null;
/**
 * Disambiguation, e.g. the local authority
 */
export type Detail1 = string | null;
export type Kind = "postcode" | "place" | "lsoa" | "msoa" | "lad" | "region";
export type Lsoa21Cd2 = string | null;
export type Name4 = string;
export type Category1 = string;
export type OriginLabel = string;
export type Pois1 = Poi[];
export type Bbox3 = [unknown, unknown, unknown, unknown] | null;
/**
 * Areas that passed the filters
 */
export type Candidates = number;
export type Level1 = "lsoa" | "msoa" | "lad" | "region";
export type Preset4 = string;
export type Code3 = string;
export type Level2 = "lsoa" | "msoa" | "lad" | "region";
export type LocalAuthority1 = string;
export type MedianPrice = number | null;
export type Name5 = string;
export type Overall3 = number | null;
export type OverallPercentile3 = number | null;
export type Population1 = number;
export type Rank = number;
export type Results = RankedArea[];
/**
 * The area or place the ranking was limited to
 */
export type Within = string | null;

export interface Schemas {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Schemas`'s JSON-Schema
 * via the `definition` "AreaProfile".
 */
export interface AreaProfile {
  band?: Band;
  bbox: Bbox;
  centre: Point;
  coverage: Coverage;
  flags?: Flags;
  key_facts: KeyFacts;
  local_authority: LocalAuthority;
  lsoa21cd: Lsoa21Cd;
  lsoa_name: LsoaName;
  msoa21cd: Msoa21Cd;
  neighbourhood?: Neighbourhood;
  overall: Overall;
  overall_percentile: OverallPercentile;
  population: Population;
  preset: Preset;
  region: Region;
  strengths: Strengths;
  themes: Themes;
  urban_rural: UrbanRural;
  weaknesses: Weaknesses;
}
/**
 * This interface was referenced by `Schemas`'s JSON-Schema
 * via the `definition` "Point".
 */
export interface Point {
  lat: Lat;
  lon: Lon;
}
/**
 * This interface was referenced by `Schemas`'s JSON-Schema
 * via the `definition` "IndicatorValue".
 */
export interface IndicatorValue {
  id: Id;
  label: Label;
  quality?: Quality;
  role?: Role;
  score?: Score;
  theme: Theme;
  unit: Unit;
  value?: Value;
}
/**
 * This interface was referenced by `Schemas`'s JSON-Schema
 * via the `definition` "ThemeScore".
 */
export interface ThemeScore {
  label: Label1;
  percentile?: Percentile;
  score?: Score1;
  theme: Theme1;
}
/**
 * This interface was referenced by `Schemas`'s JSON-Schema
 * via the `definition` "ComparedArea".
 */
export interface ComparedArea {
  code: Code;
  indicators: Indicators;
  level: Level;
  name: Name;
  overall: Overall1;
  overall_percentile: OverallPercentile1;
  themes: Themes1;
}
/**
 * Raw indicator values
 */
export interface Indicators {
  [k: string]: number | null;
}
export interface Themes1 {
  [k: string]: number | null;
}
/**
 * This interface was referenced by `Schemas`'s JSON-Schema
 * via the `definition` "Comparison".
 */
export interface Comparison {
  areas: Areas;
  indicator_labels: IndicatorLabels;
  preset: Preset1;
  theme_labels: ThemeLabels;
}
export interface IndicatorLabels {
  [k: string]: string;
}
export interface ThemeLabels {
  [k: string]: string;
}
/**
 * This interface was referenced by `Schemas`'s JSON-Schema
 * via the `definition` "Contribution".
 */
export interface Contribution {
  contribution?: Contribution1;
  indicators: Indicators1;
  label: Label2;
  score: Score2;
  theme: Theme2;
  weight_share: WeightShare;
}
/**
 * This interface was referenced by `Schemas`'s JSON-Schema
 * via the `definition` "Explanation".
 */
export interface Explanation {
  caveats: Caveats;
  contributions: Contributions;
  lsoa21cd: Lsoa21Cd1;
  name: Name1;
  overall: Overall2;
  overall_percentile: OverallPercentile2;
  preset: Preset2;
  sources: Sources;
}
/**
 * This interface was referenced by `Schemas`'s JSON-Schema
 * via the `definition` "IndicatorInfo".
 */
export interface IndicatorInfo {
  caveats?: Caveats1;
  description: Description;
  direction: Direction;
  id: Id1;
  label: Label3;
  normalise: Normalise;
  role: Role1;
  sources: Sources1;
  theme: Theme3;
  unit: Unit1;
  weight: Weight;
}
/**
 * This interface was referenced by `Schemas`'s JSON-Schema
 * via the `definition` "LiveabilityState".
 */
export interface LiveabilityState {
  compare_within_urban_rural?: CompareWithinUrbanRural;
  indicator_weights?: IndicatorWeights;
  map?: MapView;
  mode?: Mode;
  preset?: Preset3;
  shortlist?: Shortlist;
  theme_weights?: ThemeWeights;
}
/**
 * Multipliers on individual indicators
 */
export interface IndicatorWeights {
  [k: string]: number;
}
/**
 * This interface was referenced by `Schemas`'s JSON-Schema
 * via the `definition` "MapView".
 */
export interface MapView {
  bbox?: Bbox1;
  highlighted?: Highlighted;
  layer?: Layer;
  pois?: Pois;
  selected?: Selected;
}
/**
 * This interface was referenced by `Schemas`'s JSON-Schema
 * via the `definition` "Poi".
 */
export interface Poi {
  category: Category;
  detail?: Detail;
  distance_m: DistanceM;
  licence: Licence;
  name: Name2;
  point: Point;
  source: Source;
}
export interface Detail {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Schemas`'s JSON-Schema
 * via the `definition` "ShortlistItem".
 */
export interface ShortlistItem {
  centre?: Point | null;
  code: Code1;
  name: Name3;
  note?: Note;
}
/**
 * Overrides on top of the preset's theme weights
 */
export interface ThemeWeights {
  [k: string]: number;
}
/**
 * A search result: something a user might mean by a name, postcode or code.
 *
 * This interface was referenced by `Schemas`'s JSON-Schema
 * via the `definition` "Place".
 */
export interface Place {
  bbox?: Bbox2;
  centre?: Point | null;
  code?: Code2;
  detail?: Detail1;
  kind: Kind;
  lsoa21cd?: Lsoa21Cd2;
  name: Name4;
}
/**
 * This interface was referenced by `Schemas`'s JSON-Schema
 * via the `definition` "PoiResult".
 */
export interface PoiResult {
  category: Category1;
  origin: Point;
  origin_label: OriginLabel;
  pois: Pois1;
}
/**
 * This interface was referenced by `Schemas`'s JSON-Schema
 * via the `definition` "RankResult".
 */
export interface RankResult {
  bbox?: Bbox3;
  candidates: Candidates;
  level: Level1;
  preset: Preset4;
  results: Results;
  theme_weights: ThemeWeights1;
  within?: Within;
}
/**
 * This interface was referenced by `Schemas`'s JSON-Schema
 * via the `definition` "RankedArea".
 */
export interface RankedArea {
  centre: Point;
  code: Code3;
  level: Level2;
  local_authority: LocalAuthority1;
  median_price?: MedianPrice;
  name: Name5;
  overall: Overall3;
  overall_percentile: OverallPercentile3;
  population: Population1;
  rank: Rank;
  themes: Themes2;
}
export interface Themes2 {
  [k: string]: number | null;
}
export interface ThemeWeights1 {
  [k: string]: number;
}
