"""Generate docs/data-sources.md and ATTRIBUTION.md from the dataset registry.

Run ``lix docs`` after editing config/datasets.yaml; CI can check the files are current.
"""

from collections import defaultdict

from lix_core.config import NATION_NAMES, DatasetSpec, load_registry
from lix_core.paths import get_project_root

THEME_TITLES = {
    "geography": "Geography",
    "safety": "Safety",
    "environment": "Environment",
    "health": "Health access",
    "education": "Education & childcare",
    "transport": "Transport & connectivity",
    "amenities": "Amenities & nightlife",
    "housing": "Housing & affordability",
    "community": "Community & socio-economic",
}

HEADER = "<!-- Generated by `lix docs` from config/datasets.yaml; do not edit by hand. -->\n\n"


def _cell(text: str | None) -> str:
    return (text or "").replace("|", "\\|").replace("\n", " ").strip()


def _link(spec: DatasetSpec) -> str:
    url = (
        spec.landing_page or getattr(spec.access, "url", None) or getattr(spec.access, "page", None)
    )
    return f"[{_cell(spec.title)}]({url})" if url else _cell(spec.title)


def data_sources_md(registry: dict[str, DatasetSpec]) -> str:
    by_theme: dict[str, list[tuple[str, DatasetSpec]]] = defaultdict(list)
    for slug, spec in registry.items():
        by_theme[spec.theme].append((slug, spec))

    lines = [
        HEADER + "# Data sources\n",
        f"{len(registry)} datasets, all under open licences. Each is pinned to a concrete file "
        "in `config/datasets.lock.json` by `lix resolve`.\n",
    ]
    for theme, title in THEME_TITLES.items():
        if theme not in by_theme:
            continue
        lines.append(f"\n## {title}\n")
        lines.append("| Slug | Dataset | What it gives us | Covers | Updated | Licence |")
        lines.append("|---|---|---|---|---|---|")
        for slug, spec in by_theme[theme]:
            licence = spec.licence + ("" if spec.licence_verified else " (unverified)")
            priority = "" if spec.priority == "P0" else f" ({spec.priority})"
            covers = ", ".join(NATION_NAMES[n] for n in spec.coverage)
            lines.append(
                f"| `{slug}`{priority} | {_link(spec)} | {_cell(spec.description)} "
                f"| {covers} | {spec.cadence} | {licence} |"
            )
    return "\n".join(lines) + "\n"


def attribution_md(registry: dict[str, DatasetSpec]) -> str:
    seen: dict[str, list[str]] = {}
    for slug, spec in registry.items():
        seen.setdefault(spec.attribution.strip(), []).append(slug)
    lines = [
        HEADER + "# Attribution\n",
        "This project's outputs are built from the datasets below. Reuse must keep these "
        "notices. Data derived from OpenStreetMap is a derivative database under the Open "
        "Database Licence (ODbL) and must be shared under the same licence.\n",
    ]
    for text, slugs in seen.items():
        lines.append(f"- {text} ({', '.join(f'`{s}`' for s in slugs)})")
    return "\n".join(lines) + "\n"


def write_docs() -> list[str]:
    root = get_project_root()
    registry = load_registry()
    (root / "docs").mkdir(exist_ok=True)
    outputs = {
        root / "docs" / "data-sources.md": data_sources_md(registry),
        root / "ATTRIBUTION.md": attribution_md(registry),
    }
    for path, text in outputs.items():
        path.write_text(text)
    return [str(p.relative_to(root)) for p in outputs]
